doc: generate ordered API list for metrics doc
NetApp/harvest pull request #2458
Opened 2023-11-03 11:25 UTC by rahulguptajss

2023-11-03 11:51 UTC, cgrinds requested changes

2023-11-03 11:51 UTC, cgrinds commented on cmd/tools/generate/counter.go
> +	restKeys := sortedKeys(restCounters)
restKeys := maps.Keys(restCounters)

slices.Sort(restKeys)

2023-11-03 12:06 UTC, cgrinds commented on cmd/tools/generate/counter.go
> +	sort.Strings(zapiKeys)
not needed?

2023-11-03 12:06 UTC, cgrinds commented on cmd/tools/generate/counter.go
> +	sort.Strings(keys)
slices.Sort is better to use since it is faster

2023-11-03 12:27 UTC, Hardikl submitted a review, later dismissed

2023-11-03 12:27 UTC, Hardikl commented on docs/ontap-metrics.md
> +
empty description?

2023-11-03 13:41 UTC, Hardikl approved these changes

2023-11-07 17:06 UTC, cgrinds approved these changes

2023-11-07 17:06 UTC, merged