feat: log zapi request/response
NetApp/harvest pull request #382
Opened 2021-08-04 21:12 UTC by cgrinds

when a `poller` includes a `log` section, the matching collector will log that collector's zapi request/response

e.g.

```
Pollers:
  infinity:
    datacenter: ctl
    addr: 10.10.10.10
    log:
      - Zapi                <==== the Zapi collector should log each ZAPI's request/response
      - ZapiPerf         <==== the ZapiPerf collector should do the same
```

2021-08-04 21:59 UTC, cdurai-netapp commented on pkg/api/ontapi/zapi/client.go
> +			}
may be we can stop the loop after EqualFold return true to stop the iterations further.

2021-08-04 22:00 UTC, cdurai-netapp approved these changes

2021-08-05 01:38 UTC, cdurai-netapp submitted a review, later dismissed

2021-08-05 09:02 UTC, Hardikl approved these changes

2021-08-05 09:02 UTC, Hardikl commented on cmd/collectors/zapi/collector/zapi.go
> +	me.Client.TraceLogSet(me.Name, me.Params)
add comment

2021-08-05 09:33 UTC, vgratian requested changes
good job, 

let's doc this, I would just add a new line [in the list of poller parameters](https://github.com/NetApp/harvest#pollers):

```
| `log`  | optional, list  | Log API requests and responses for the collectors listed (currently only Zapi and ZapiPerf supported) | |
```

2021-08-05 09:36 UTC, vgratian commented
> good job,
> 
> let's doc this, I would just add a new line [in the list of poller parameters](https://github.com/NetApp/harvest#pollers):
> 
> ```
> | `log`  | optional, list  | Log API requests and responses for the collectors listed (currently only Zapi and ZapiPerf supported) | |
> ```

note to self: let's also remember to support this parameter in the rest client

2021-08-05 12:12 UTC, merged